// GENERATED by scripts/write-deployments-module.mjs — do not edit.
// Source of truth: deployments.json at the repo root, written by
// scripts/deploy.sh. Regenerate with `./scripts/deploy.sh <network>`.

export type NetworkId = 'testnet' | 'mainnet';

export const NETWORK_IDS = ['testnet', 'mainnet'] as const;

/**
 * Where the app starts, and where it falls back to when anything about the
 * stored or requested network is not understood. It is testnet on purpose:
 * every unknown value must land somewhere that cannot spend real money.
 */
export const DEFAULT_NETWORK: NetworkId = 'testnet';

export const DEPLOYMENTS = {
  testnet: {
    id: 'testnet',
    networkPassphrase: 'Test SDF Network ; September 2015',
    rpcUrl: 'https://soroban-testnet.stellar.org',
    horizonUrl: 'https://horizon-testnet.stellar.org',
    /** Testnet only. `null` is how the faucet knows it has no meaning here. */
    friendbotUrl: 'https://friendbot.stellar.org',
    /** stellar.expert's path segment: 'testnet' or 'public'. */
    explorerPath: 'testnet',
    deployedAt: '2026-09-21T06:53:57.747Z',
    /** Backend hot key: signs settle and refund (and mints, on testnet). */
    resolver: 'GBGMPRHU3NW3BCXUNDNC7VSYQKS6FZKWFHSGEHHMR3G3TZOUWEDBHTFK',
    /** Where a settled order's USDC ends up. The app never signs for it. */
    treasury: 'GAXUICH5DZMB4ZIZVF6ETTE524RCZYRKHWLGG7EOLY6ECVD4IS6TBNZG',
    escrowId: 'CBCUESHDKRXAH4YAHOKJFRFEOIYBTU2LYJ4LCOFIGMYGNHBCPACXQ557',
    usdcId: 'CB63C7UVZ3PBALQ7IE37QU2ZX5X3UMTLJOHDRI2EW44JU26YDGLQUBJF',
    /**
     * The classic asset the SAC wraps, when it wraps one. `null` on testnet,
     * where contracts/mock_usdc is a pure SEP-41 token with no issuer — which
     * is exactly why testnet needs no trustline and a public network does.
     */
    usdcIssuer: null,
    usdcCode: 'USDC',
    usdcDecimals: 7,
  },
  mainnet: {
    id: 'mainnet',
    networkPassphrase: 'Public Global Stellar Network ; September 2015',
    rpcUrl: 'https://mainnet.sorobanrpc.com',
    horizonUrl: 'https://horizon.stellar.org',
    /** Testnet only. `null` is how the faucet knows it has no meaning here. */
    friendbotUrl: null,
    /** stellar.expert's path segment: 'testnet' or 'public'. */
    explorerPath: 'public',
    deployedAt: null,
    /** Backend hot key: signs settle and refund (and mints, on testnet). */
    resolver: '',
    /** Where a settled order's USDC ends up. The app never signs for it. */
    treasury: '',
    escrowId: '',
    usdcId: '',
    /**
     * The classic asset the SAC wraps, when it wraps one. `null` on testnet,
     * where contracts/mock_usdc is a pure SEP-41 token with no issuer — which
     * is exactly why testnet needs no trustline and a public network does.
     */
    usdcIssuer: 'GA5ZSEJYB37JRC5AVCIA5MOP4RHTM335X2KGX3IHOJAPP5RE34K4KZVN',
    usdcCode: 'USDC',
    usdcDecimals: 7,
  },
} as const;

export type Deployment = (typeof DEPLOYMENTS)[NetworkId];

/** Narrows an untrusted string — a query param, localStorage — to a network. */
export function asNetwork(value: unknown): NetworkId | null {
  return typeof value === 'string' && (NETWORK_IDS as readonly string[]).includes(value)
    ? (value as NetworkId)
    : null;
}

/** Same, but never fails: anything unrecognised becomes the default. */
export function networkOrDefault(value: unknown): NetworkId {
  return asNetwork(value) ?? DEFAULT_NETWORK;
}

/** True once the contracts and accounts for this network actually exist. */
export function isConfigured(net: NetworkId): boolean {
  const d = DEPLOYMENTS[net];
  return Boolean(d.escrowId && d.usdcId && d.resolver && d.treasury);
}

/**
 * The config, or a refusal naming the network. Called by everything that is
 * about to talk to a chain, so an undeployed network fails here rather than as
 * an unreadable XDR error from a contract client built with an empty id.
 */
export function deployment(net: NetworkId): Deployment {
  if (!isConfigured(net)) {
    throw new Error(`No hay contratos desplegados en ${net}. Corré ./scripts/deploy.sh ${net}.`);
  }
  return DEPLOYMENTS[net];
}
