// GENERATED by scripts/write-deployments-module.mjs — do not edit.
// Source of truth: deployments.json at the repo root, written by
// scripts/deploy-testnet.sh. Regenerate with `./scripts/deploy-testnet.sh`.
//
// Deployed 2026-09-21T06:53:57.747Z.

export const DEPLOYMENTS = {
  network: 'testnet',
  networkPassphrase: 'Test SDF Network ; September 2015',
  rpcUrl: 'https://soroban-testnet.stellar.org',
  /** Backend hot key: mints demo USDC, signs settle and refund. */
  resolver: 'GBGMPRHU3NW3BCXUNDNC7VSYQKS6FZKWFHSGEHHMR3G3TZOUWEDBHTFK',
  /** Where a settled order's USDC ends up. The app never signs for it. */
  treasury: 'GAXUICH5DZMB4ZIZVF6ETTE524RCZYRKHWLGG7EOLY6ECVD4IS6TBNZG',
  escrowId: 'CBCUESHDKRXAH4YAHOKJFRFEOIYBTU2LYJ4LCOFIGMYGNHBCPACXQ557',
  usdcId: 'CB63C7UVZ3PBALQ7IE37QU2ZX5X3UMTLJOHDRI2EW44JU26YDGLQUBJF',
  usdcDecimals: 7,
} as const;
